apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: insurance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: sachin820/frontend:V1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: insurance
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80

